//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wypozyczalnia.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Wyporzyczenias = new HashSet<Wyporzyczenia>();
        }
    
        public int Id { get; set; }
        public string Tytul { get; set; }
        public int IdAutor { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Film Film1 { get; set; }
        public virtual Film Film2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wyporzyczenia> Wyporzyczenias { get; set; }
    }
}
