//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wypozyczalnia.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wyporzyczenia
    {
        public int Id { get; set; }
        public int IdFilm { get; set; }
        public int IdKlient { get; set; }
        public System.DateTime DataDo { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Klient Klient { get; set; }
    }
}
